### ISSUE TITLE
Individual Lab details 

### ISSUE THREAD

**Issue by dwijaybane** [ELSPL/ml-community#10]
There is a README in each LAB
populate with information on that LAB
Provide a sequence to examples involved in that LAB
Give detailed information on each exercises.

**Comment by dwijaybane** [comment]
Kudos for arranging labs :+1:

**Comment by JayParanjape** [comment]
@dwijaybane Have a look at the individual READMEs for the Labs. Hope this solves the issue

**Comment by dwijaybane** [comment]
Yeah looks good !!!
